services:
  mongodb:
    image: mongo:latest
    container_name: 3city_mongodb
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - data:/data

  mongo-express:
    image: mongo-express:latest
    container_name: 3city_mongo_express
    restart: always
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongodb

# Define named volumes
volumes:
  data: {}

networks:
  default:
    name: 3city_mongodb_network