spring:
  application:
    name: "job4devs"
  profiles:
    active: "dev"
  config:
    import: "optional:configserver:http://localhost:8888"

management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8080

css:
  query:
    for:
      employer: "div.css-u51ts9"
      workplace: "div.css-1seeldo"
      position: "div.css-vb54bv > h1"
      detail: "div.css-6q28fo > div"
      skill: "h6.MuiTypography-root.MuiTypography-subtitle2"
      level: "span.MuiTypography-root.MuiTypography-subtitle4"